version: "3.8"
services:
  start:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    command: "bash ./main.sh"
  test:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 3000:3000
    env_file:
      - .test.env
    command: "go test ./..."
