version: "3.8"
services:
  start:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    command: "bash ./main.sh"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'

  test:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file:
      - .test.env
    command: "bash ./test.sh"
