version: "3.8"
services:
  postgres:
    container_name: ${DB_HOST}
    image: postgres
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    depends_on:
      - postgres
    command: "bash ./ci.sh"
